branch-defaults:
  master:
    environment: null
global:
  application_name: playgroundApp
  branch: null
  default_ec2_keyname: aws-sundar
  default_platform: Python 3.4
  default_region: ap-southeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
